import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Preahvihear } from "next/font/google";
import "./globals.css";

const preahvihear = Preahvihear({
  variable: "--font-preahvihear",
  subsets: ["latin"],
  weight: "400",
});

const Popines=Poppins({
  subsets:["latin"],
  weight:["400","700"],
  variable:"--font-popines"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${preahvihear.className} ${Popines.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
